# Generated by Django 4.2.14 on 2024-08-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='customer',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='date_sale',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='ventas',
            old_name='total_sale',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
