# Generated by Django 4.2.14 on 2024-08-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_remove_product_descripcion_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.FileField(upload_to='productos/'),
        ),
    ]
